#!/usr/bin/expect -f
log_user 1

set timeout 10;
set user {ubuntu}
set local_dir {~/Pets/number_zero/src/*}
set remote_dir {~/number_zero/src/}
set ip {192.168.1.4}

send "\n"
spawn bash -c "rsync -avzP --no-perms --no-owner --no-group $local_dir $user@$ip:$remote_dir"
interact