#!/usr/bin/expect -f
log_user 1

set timeout 10;
set PATH $::env(NUMBER_ZERO_PATH)

set user [exec $PATH/parse_config $PATH/config/general.yml remote login_name]
set local_dir {~/Pets/number_zero/src/*}
set remote_dir {~/number_zero/src/}
set ip [exec $PATH/parse_config $PATH/config/general.yml remote ip]

puts "Syncing with $ip ..."

send "\n"
spawn bash -c "rsync -avzP --no-perms --no-owner --no-group $local_dir $user@$ip:$remote_dir"
interact