#!/usr/bin/expect -f
log_user 0

set timeout 10;
set PATH $::env(NUMBER_ZERO_PATH)

set user [exec $PATH/parse_config $PATH/config/general.yml remote login_name]
set local_dir "$PATH/*"
set remote_dir "~/number_zero/"
set ip [ exec $PATH/parse_config $PATH/config/general.yml remote ip ]
set exc "{bashme_to_internet_share,ssh_remote,sync_remote,general.yml,*.pyc}"

puts "Syncing $local_dir to $remote_dir with $ip as $user ..."

puts -nonewline "The following will be updated: "
spawn bash -c "rsync -avzPn --no-perms --no-owner --no-group --exclude=$exc $local_dir $user@$ip:$remote_dir"
flush stdout

interact
puts "\nDo you want to proceed \[y/N]?"
set response [gets stdin]

if {$response == "y" } {
spawn bash -c "rsync -avzP --no-perms --no-owner --no-group --exclude=$exc $local_dir $user@$ip:$remote_dir"
interact
}
