#!/usr/bin/expect -f
log_user 0
set timeout 10;

proc usage {} {
    puts {Syncs the files between this computer and a remote.}
    puts {Usage: sync_remote [force]}
    exit
}

if { $argv == "--help" } {
    usage
}

set PATH $::env(NUMBER_ZERO_PATH)

set user [exec $PATH/parse_config $PATH/config/general.yml remote login_name]
set local_dir "$PATH/*"
set remote_dir "~/number_zero/"
set ip [ exec $PATH/parse_config $PATH/config/general.yml remote ip ]
set exc [ exec $PATH/parse_config $PATH/config/sync.yml excludes ]

puts "Syncing $local_dir to $remote_dir with $ip as $user ..."

if {$argv != "force"} {
    puts "The following will be updated:"
    puts "=============================="

    spawn bash -c "rsync -avzPn --no-perms --no-owner --no-group --exclude=$exc --delete-before $local_dir $user@$ip:$remote_dir"
    flush stdout

    interact
    puts "=============================="
    puts -nonewline "Do you want to proceed [y/N]? "
    flush stdout
    set response [gets stdin]
}


if {($argv == "force") || ($response == "y")} {
    spawn bash -c "rsync -avzP --no-perms --no-owner --no-group --exclude=$exc --delete-before $local_dir $user@$ip:$remote_dir"
    interact
}
